### PR TITLE
add jsonserialize for address and address validate

### PR DESCRIPTION
**Pull request by bullder**

### CODE REVIEW

**Comment by bullder** [comment]
also it would be great add any tag to repository

**Comment by bkuhl** [comment]
:+1: Thanks!

**Comment by hppycoder** [comment]
@bkuhl @Ruskicowboy - The big problem I see here is that this just bumped the required PHP version to 5.4.0 as JsonSerializer is only in the PHP 5.4 and above. That being said could we consider using JMSSerializer for this instead? Put it as a required inside of the composer.json file and use that.

I think this is really great, and having the library be the only one for UPS that still works with PHP 5.3 is a huge benefit. Our codebase at this point in time is in PHP 5.3 and is not scheduled to upgrade until early 2017.

Thanks,
Chad

**Comment by bkuhl** [comment]
Good catch.  The `1.x` branch will continue with PHP 5.3 compatible releases.  `master` will be continued on later versions of php.

With PHP 5.5 soon to be end of life I don't think it's a good idea to choose dependencies to maintain 5.3 compatibility.

**Comment by hppycoder** [comment]
I understand, what sets your code apart from the others found in Packagist is that it's the only one who supports PHP 5.3 with it's current version.

The competitive advantage would be lost moving your code to PHP 5.5+ and removing PHP 5.3/5.4 support. You can do what you want as the maintainer but I just want to highlight the fact that this repo is the only PHP 5.3 version left for UPS.

**Comment by bkuhl** [comment]
👍 I appreciate the feedback.  I'll indicate on the readme that PHP 5.3 is supported by 1.x versions.

**Pull request merged**
